package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Folder;
import greendao.Photo;

import greendao.FolderDao;
import greendao.PhotoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig folderDaoConfig;
    private final DaoConfig photoDaoConfig;

    private final FolderDao folderDao;
    private final PhotoDao photoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        folderDaoConfig = daoConfigMap.get(FolderDao.class).clone();
        folderDaoConfig.initIdentityScope(type);

        photoDaoConfig = daoConfigMap.get(PhotoDao.class).clone();
        photoDaoConfig.initIdentityScope(type);

        folderDao = new FolderDao(folderDaoConfig, this);
        photoDao = new PhotoDao(photoDaoConfig, this);

        registerDao(Folder.class, folderDao);
        registerDao(Photo.class, photoDao);
    }
    
    public void clear() {
        folderDaoConfig.getIdentityScope().clear();
        photoDaoConfig.getIdentityScope().clear();
    }

    public FolderDao getFolderDao() {
        return folderDao;
    }

    public PhotoDao getPhotoDao() {
        return photoDao;
    }

}
